name: to_do
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - l10n/
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500