name: to_do
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

isar_version: 3.1.0 

dependencies:
  device_info: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^1.4.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - l10n/
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500