// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOS_ohXZlohiWBOTDFfG8RvqH-Pq7M2g',
    appId: '1:1052004457191:web:143ae045af608d78b4e042',
    messagingSenderId: '1052004457191',
    projectId: 'yandex-todo-eb9e0',
    authDomain: 'yandex-todo-eb9e0.firebaseapp.com',
    storageBucket: 'yandex-todo-eb9e0.appspot.com',
    measurementId: 'G-J5KQTNM9B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDe8S79LR-pQ5Hq2Ly6CP_ho4MFROQQlI',
    appId: '1:1052004457191:android:7769da3a441fe3b5b4e042',
    messagingSenderId: '1052004457191',
    projectId: 'yandex-todo-eb9e0',
    storageBucket: 'yandex-todo-eb9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNY8qctN2rivY1mL6qV1yGYIM2sWDW09A',
    appId: '1:1052004457191:ios:005c36093e8d5d8eb4e042',
    messagingSenderId: '1052004457191',
    projectId: 'yandex-todo-eb9e0',
    storageBucket: 'yandex-todo-eb9e0.appspot.com',
    iosClientId:
        '1052004457191-79kpstmv9220ot6b23oac2vhhtpb8m56.apps.googleusercontent.com',
    iosBundleId: 'com.example.shmrTodo',
  );
}
